import { useEffect, useMemo, useState } from 'react';
import { Navigate, Route, Routes, useParams, useSearchParams } from 'react-router-dom';
import { ArrowUpRight } from 'lucide-react';
import { architects, adebayoProjects, featuredProjects, reviews } from './data/architects';
import { Layout } from './components/Layout';
import { ArchitectCard, ProjectCard } from './components/Cards';
import { ConsultationModal } from './components/ConsultationModal';
import { Account, ArchitectApply, ProjectStart, Received } from './components/AccountFlows';
import { Dashboard } from './components/Dashboard';
import { ConsultationRequest } from './components/ConsultationRequest';
import { database } from './lib/supabase';
import type { Specialty } from './types';

function Home(){return <Layout><section className="hero"><img src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2200&q=90" alt="Contemporary architectural residence"/><div className="hero-copy"><p className="mono hero-index">01—26<br/>CURATED<br/>STUDIOS</p><h1>Find your<br/><em>form.</em></h1><div><p>The thoughtful way to find an architect who sees what you see.</p><a href="/architects" className="outline-button">Explore architects <ArrowUpRight size={17}/></a></div></div></section><section className="intro split"><p className="mono">[ 01 / THE BETTER BEGINNING ]</p><div><h2>A beautiful project begins with <em>the right mind.</em></h2><p>Formline is a considered marketplace for clients with a point of view and architects who turn it into a place worth inhabiting.</p></div></section><section className="section"><div className="section-head"><div><p className="mono">[ 02 / MEET THE PRACTICE ]</p><h2>For every point of view.</h2></div><a href="/architects">View all architects ↗</a></div><div className="card-grid three">{architects.slice(0,3).map(architect=><ArchitectCard key={architect.slug} architect={architect}/>)}</div></section><section className="projects-dark"><div className="split"><p className="mono">[ 03 / IN THE MAKING ]</p><div><h2>Spaces with a<br/><em>sense of themselves.</em></h2><p>Explore what happens when an exceptional brief meets a singular practice.</p></div></div><div className="project-grid">{featuredProjects.map((project,i)=><ProjectCard key={project.title} project={project} offset={i===1}/>)}</div></section><Process/><Cta/></Layout>}
function Process(){return <section className="section split"><p className="mono">[ 04 / A SIMPLER WAY ]</p><div><h2>A considered match,<br/>from first thought to <em>first sketch.</em></h2><div className="steps">{[['01','Tell us what matters','Share your site, your ambitions and the feeling you want your space to hold.'],['02','Meet your shortlist','We make thoughtful introductions to practices that are right for the brief.'],['03','Make something lasting','Choose with clarity, then begin a project built on a shared point of view.']].map(s=><div className="step" key={s[0]}><span className="mono">{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></div></section>}
function Cta(){return <section className="cta"><h2>Your next space starts <em>here.</em></h2><div><p>Whether you’re building from the ground up or changing the way you live, the right collaborator changes everything.</p><a className="dark-button" href="/start-project">Start your project ↗</a></div></section>}
function Architects(){const [live,setLive]=useState<{id:string;studio_name:string;city:string|null;specialty:string|null;bio:string|null}[]>([]);const [loading,setLoading]=useState(true);const [searchParams]=useSearchParams();const brief=searchParams.get('brief')||'';useEffect(()=>{database.select<{id:string;studio_name:string;city:string|null;specialty:string|null;bio:string|null}>('architect_profiles','select=id,studio_name,city,specialty,bio&application_status=eq.approved&order=created_at.desc','').then(setLive).finally(()=>setLoading(false))},[]);return <Layout><section className="directory-hero"><p className="mono">[ VERIFIED DIRECTORY ]</p><div><h1>Architects with <em>a point</em> of view.</h1><p>Independent practices verified by Formline, ready for considered new enquiries.{brief?` Your saved brief will follow your selection.`:''}</p></div></section><section className="section"><div className="card-grid three">{live.map(a=><article className="architect-card" key={a.id}><div className="image-wrap"><div style={{height:380,background:'#d8d7d0'}}/></div><div className="card-foot"><div><h3>{a.studio_name}</h3><span className="mono">{a.city||'Location coming soon'} · {a.specialty||'Architecture'}</span><p className="rating">{a.bio||'A verified Formline practice.'}</p></div><a className="round-arrow" href={`/consult/${a.id}${brief?`?brief=${brief}`:''}`}>↗</a></div></article>)}</div>{!loading&&!live.length&&<div className="empty"><h3>The first verified practices are arriving.</h3><p>Architect profiles will appear here only after an admin approval.</p><a className="dark-button" href="/apply">Apply as an architect →</a></div>}</section><section className="cta"><h2>Not sure who fits? <em>We’ll help.</em></h2><div><p>Start with a concise project brief, then send it only to practices whose work feels aligned.</p><a className="dark-button" href="/start-project">Create your brief ↗</a></div></section></Layout>}
function ArchitectProfile(){const {slug}=useParams();const architect=architects.find(a=>a.slug===slug);const [modal,setModal]=useState(false);if(!architect)return <Navigate to="/architects" replace/>;const work=architect.slug==='maison-adebayo'?adebayoProjects:adebayoProjects.map((p,i)=>({...p,title:i===0?`${architect.name} Residence`:p.title}));return <Layout><section className="profile-hero"><a className="mono back" href="/architects">← ALL ARCHITECTS</a><div><p className="mono">{architect.location} · EST. {architect.founded}</p><h1>{architect.name.split(' ').map((w,i)=><span key={w} className={i===1?'serif':''}>{w}{i===0?<br/>:'.'}</span>)}</h1></div><div><p>{architect.description}</p><div className="stats"><p><b>{architect.rating.toFixed(1)} <span>★★★★★</span></b><small>{architect.reviews} verified reviews</small></p><p><b>{architect.years} years</b><small>of practice</small></p><p><b>18–36 mo.</b><small>typical timeline</small></p></div></div></section><img className="profile-cover" src={architect.image} alt={architect.name}/><section className="section split"><p className="mono">[ THE STUDIO ]</p><div><h2>We make spaces that are <em>generous</em> in their restraint.</h2><div className="copy-columns"><p>{architect.name} is an architecture and interior design practice creating contemporary buildings with a deep sensitivity to climate, craft and the rituals of everyday life.</p><p>Based in {architect.location.split(',')[0]} and working internationally, the studio moves from the first sketch to the last carefully chosen handle.</p></div><div className="facts"><div><small>FOUNDED</small><b>{architect.founded}</b></div><div><small>TEAM</small><b>12 people</b></div><div><small>PROJECTS</small><b>48 completed</b></div><div><small>LANGUAGES</small><b>EN · FR · YO</b></div></div></div></section><section className="projects-dark"><div className="section-head"><div><p className="mono">[ SELECTED WORK ]</p><h2>A catalog of <em>belonging.</em></h2></div></div><div className="project-grid">{work.map((project,i)=><ProjectCard key={project.title} project={project} offset={i%2===1}/>)}</div></section><section className="section split"><div><p className="mono">[ CLIENT NOTES ]</p><p className="score">{architect.rating.toFixed(1)}<span>★</span></p><p className="muted">Average from {architect.reviews} verified clients</p></div><div className="review-list">{reviews.map(r=><article key={r.author}><p>“{r.quote}”</p><small className="mono">{r.author} · {r.project} · {r.year}</small></article>)}</div></section><section className="cta"><h2>Could this be the <em>right fit?</em></h2><div><p>Book a 30-minute introduction to discuss your project, the site and what you’re hoping to create.</p><button className="dark-button" onClick={()=>setModal(true)}>Request a consultation ↗</button></div></section>{modal&&<ConsultationModal studio={architect.name} onClose={()=>setModal(false)}/>}</Layout>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/architects" element={<Architects/>}/><Route path="/architects/:slug" element={<ArchitectProfile/>}/><Route path="/account" element={<Account/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/apply" element={<ArchitectApply/>}/><Route path="/start-project" element={<ProjectStart/>}/><Route path="/consult/:architectId" element={<ConsultationRequest/>}/><Route path="/application-received" element={<Received type="application"/>}/><Route path="/brief-received" element={<Received type="brief"/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
